### ISSUE TITLE
003_opengl エラー: failed to convert to compilation log from buffer

### ISSUE THREAD

**Issue by yasuhito** [toyamaguchi/rust_opengl#1]
003_opengl で `cargo run` すると以下のエラーになります。

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/sdl`
OK: init OpenGL: version=3.1
thread 'main' panicked at 'failed to convert to compilation log from buffer: invalid utf-8 sequence of 1 bytes from index 58', src/shader.rs:131:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

修正方法がわかればお願いいたします。

使用している環境はこちらです:
- OS: macOS Ventura 13.3.1
- Rust 1.71.1

**Comment by toyamaguchi** [comment]
お返事遅くなってすいません。

できるだけサポートしたい気持ちではあるのですが、手元にMacの環境がないため確認が難しい状況です。
取り急ぎ、今回のエラーメッセージから原因のヒントとなる情報を考えてみたいと思います。

エラーメッセージによると、Vertex Shaderのソースコードである「shader.vs」のコンパイルに失敗しているようですね。
該当箇所は58文字目でエラーになっているようなので、もしソースコードを改変していないならば、次に示すソースコードの最後の行にある「uniform」の「uni」まで読み込んだところでエラーになったことになります。

```
#version 140

in vec3 iPosition;

uniform mat4 uModel;
uniform mat4 uView;
```

かなり中途半端なところでエラーになっているので、文字と文字の間に見えないバイトコードが含まれている可能性などありますでしょうか？
それか、このVertex Shaderに修正を加えた状態でしょうか？

**Comment by shingo-nakanishi** [comment]
@toyamaguchi 

Macが手元にないとのことで、調査が難しそうなことは承知しましたが、私の環境でもなりましたので、報告となります。

なお。下記に cargo run  を2回した様子を載せます。起動するたびにindexの数値が異なります（1回目は 112, 2回目は106）。
https://github.com/toyamaguchi/rust_opengl/tree/master/003_opengl をそのままダウンロードして実行しています。
VSCodeで確認したところファイルは UTF-8, 改行LFなので、文字コードは正常のはずと考えております。

```
$ cargo run  
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/sdl`
OK: init OpenGL: version=3.1
thread 'main' panicked at 'failed to convert to compilation log from buffer: invalid utf-8 sequence of 2 bytes from index 112', src/shader.rs:131:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/sdl`
OK: init OpenGL: version=3.1
thread 'main' panicked at 'failed to convert to compilation log from buffer: invalid utf-8 sequence of 1 bytes from index 106', src/shader.rs:131:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by shingo-nakanishi** [comment]
ロゼッタをOFFにしたところより詳細なエラーがでました。

```
OK: init OpenGL: version=3.1
failed to compile shader code: type=FRAGMENT, log=ERROR: 0:7: Use of undeclared identifier 'gl_FragColor'

thread 'main' panicked at 'failed to convert to link log from buffer: invalid utf-8 sequence of 1 bytes from index 64', src/shader.rs:149:33
```

gl_FragColor が原因のようですので、下記のように out 変数（？）を設けると動きました。

**shader.fs**
```
#version 140

in vec3 FragPosition;
out vec4 FragColor;

void main()
{
    FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
```

gl_FragColorは昔あった予約語（？）で、今はもう廃止されているということでしょうか？


<img width="633" alt="Screenshot 2024-01-27 at 11 24 38" src="https://github.com/toyamaguchi/rust_opengl/assets/2630601/d67dc593-b069-4733-be6b-aed690686872">

**Comment by toyamaguchi** [comment]
@shingo-nakanishi 
コメントいただいてから、私のほうでもどうやってこの現象を再現させようかとても迷っていたのですが、どうやら @shingo-nakanishi さんの発見したことが正しいようです。

私のほうでも、GLSL 1.3から`gl_FragColor`がdeprecatedになったことが語られるスレッドを発見しました。
https://community.khronos.org/t/about-gl-fragcolor-of-fragment-shader/105102

ですので、 @shingo-nakanishi さんが書いたコードのように、`out vec4 FragColor;`を入れて、main関数の中でも`FragColor`を使うようにするのが正しいようです。

私の環境はLinuxなのですが、もしかするとOpenGLの内部実装が、過去の名残でたまたま`gl_FragColor`を使用できるような状態になっていたのかもしれません。
Macの実装では、その点がきちんと仕様通りの挙動になっていて、今回の問題が起きたのかもしれませんね。

問題解決していただいて、大変感謝しております！
ありがとうございます！

**Comment by toyamaguchi** [comment]
間違えてCloseしてしまったので、Reopenしました。

念の為、今回のような方法で解決できた人が他にもいるようでしたら、このIssueもCloseしようかと思います。
